/**
 * 哪吒闹海 — Nezha Conquers the Dragon King
 * Bilingual Story Data (EN + ZH + Pinyin)
 *
 * High-school audience: complex sentences, literary vocabulary, moral depth.
 * Each chapter: { id, title{en,zh,pinyin}, image, content{en,zh,pinyin} }
 * Source: Fengshen Yanyi + 1979 Shanghai Animation Film Studio adaptation.
 */

const STORY = {
  title: {
    en: "Nezha Conquers the Dragon King",
    zh: "哪吒闹海",
    pinyin: "Nézhā Nào Hǎi"
  },
  chapters: [
    // ─────────────────────────────────────
    // Chapter 1 — The Flesh Ball
    // ─────────────────────────────────────
    {
      id: 1,
      title: {
        en: "The Flesh Ball",
        zh: "肉球降世",
        pinyin: "Ròu Qiú Jiàng Shì"
      },
      image: "chapter-1.webp",
      content: {
        en: "Deep in antiquity, when the Shang dynasty still ruled the Central Plains, the fortress of Chentang Pass stood guard over the eastern coast — a bastion of stone and bronze perched above the relentless sea. Its military commander, Li Jing, was a man caught between worlds: loyal to the Emperor above, responsible for the people below, and haunted by a pregnancy that had lasted an impossible three years and six months.\n\nAt last, one night, Lady Yin dreamed that a Daoist immortal placed something luminous in her bosom. She awoke gasping, and by morning she had given birth — but not to a child. What lay on the bed was a glistening flesh ball, round as a millstone, pulsing with a faint golden light.\n\nLi Jing, pale with dread, drew his sword and struck. The ball split open with a sound like thunder, and from within leapt a boy — bright-eyed, radiant, already able to walk and speak. On his left palm was the character 哪; on his right, 吒. The child was named Nezha.\n\nThe immortal Taiyi Zhenren descended from Kunlun Mountain, declared Nezha the reincarnation of the Spirit Pearl, and took him as his disciple. He bestowed two divine weapons: the Universe Ring, a golden circle of immense cosmic power, and the Red Armillary Sash, a crimson silk ribbon that could command the tides themselves. Thus was born the child who would shake the Dragon King\u2019s palace to its foundations.",
        zh: "远古之时，殷商王朝雄踞中原。陈塘关矗立于东海之滨，乃是一座以山石与青铜铸就的军事要塞。守关将领李靖，是一个身处两难之境的男人——对上效忠天子，对下守护百姓，同时又被一场长达三年六个月的漫长怀胎所困扰。\n\n终于，在一个月色昏沉的夜晚，殷夫人梦见一位白发道人将一粒明珠放入她的怀中。她惊醒过来，到清晨便产下了一物——然而那并非婴儿，而是一个通体泛着金色微光的肉球，圆如磨盘，隐隐跳动。\n\n李靖面色如土，拔剑劈向肉球。肉球应声而裂，光芒四射，从中跳出一个男孩——双目炯炯，神采飞扬，落地便能行走，开口便能言语。他的左掌心写着一个\u201c哪\u201d字，右掌心写着一个\u201c吒\u201d字。这孩子，便是哪吒。\n\n太乙真人自昆仑山飘然而至，称哪吒为灵珠转世，收他为徒，并赐予他两件法宝：乾坤圈——一枚蕴含无穷力量的金色圆环；混天绫——一条能够翻江倒海的赤色丝绸。于是，这个注定要震动龙宫的孩子，诞生了。",
        pinyin: "Yuǎn gǔ zhī shí, Yīn Shāng wáng cháo xióng jù zhōng yuán. Chén Táng Guān chù lì yú Dōng hǎi zhī bīn, nǎi shì yī zuò yǐ shān shí yǔ qīng tóng zhù jiù de jūn shì yào sài. Shǒu guān jiàng lǐng Lì Jìng, shì yī gè shēn chǔ liǎng nán zhī jìng de nán rén — duì shàng xiào zhōng tiān zǐ, duì xià shǒu hù bǎi xìng, tóng shí yòu bèi yī chǎng cháng dá sān nián liù gè yuè de màn cháng huái tāi suǒ kùn rǎo.\n\nZhōng yú, zài yī gè yuè sè hūn chén de yè wǎn, Yīn fū rén mèng jiàn yī wèi bái fà dào rén jiāng yī lì míng zhū fàng rù tā de huái zhōng. Tā jīng xǐng guò lái, dào qīng chén biàn chǎn xià le yī wù — rán ér nà bìng fēi yīng ér, ér shì yī gè tōng tǐ fàn zhe jīn sè wēi guāng de ròu qiú, yuán rú mó pán, yǐn yǐn tiào dòng.\n\nLì Jìng miàn sè rú tǔ, bá jiàn pī xiàng ròu qiú. Ròu qiú yìng shēng ér liè, guāng máng sì shè, cóng zhōng tiào chū yī gè nán hái — shuāng mù jiǒng jiǒng, shén cǎi fēi rán, luò dì biàn néng xíng zǒu, kāi kǒu biàn néng yán yǔ. Tā de zuǒ zhǎng xīn shàng xiě zhe yī gè哪字, yòu zhǎng xīn shàng xiě zhe yī gè吒字. Zhè hái zi, biàn shì Né zhā.\n\nTài yǐ zhēn rén zì Kūn lún shān piāo rán ér zhì, chēng Né zhā wéi líng zhū zhuǎn shì, shōu tā wéi tú, bìng cì yǔ tā liǎng jiàn fǎ bǎo: Qián kūn quān — yī méi yùn hán wú qióng lì liàng de jīn sè yuán huán; Hùn tiān líng — yī tiáo néng gòu fān jiāng dào hǎi de chì sè sī chóu. Yú shì, zhè gè zhù dìng yào zhèn dòng lóng gōng de hái zi, dàn shēng le."
      }
    },

    // ─────────────────────────────────────
    // Chapter 2 — The Dragon King's Toll
    // ─────────────────────────────────────
    {
      id: 2,
      title: {
        en: "The Dragon King\u2019s Toll",
        zh: "龙王的索求",
        pinyin: "Lóng Wáng de Suǒ Qiú"
      },
      image: "chapter-2.webp",
      content: {
        en: "Beneath the eastern waves lay the Crystal Palace of Ao Guang, Dragon King of the East Sea — a realm of coral pillars, jade-tiled halls, and cold bioluminescent light. Ao Guang was not merely a ruler of fish and tide; he was an emperor of the deep, absolute in his authority, feared by every living creature in his domain.\n\nBut Ao Guang\u2019s hunger was insatiable. He demanded tribute not only of grain, incense, and jade, but of something far more terrible: children. Every year, the people of Chentang Pass were required to send young boys and girls into the sea as offerings to the Dragon King. Those who refused faced floods, droughts, and the fury of storms that could level entire villages.\n\nThe Yaksha general Li Gen patrolled the coastal waters, his club drawn, his eyes scanning for the next tribute. Children in red festival clothes were led to the shore at dusk, weeping, their parents standing behind them with faces carved from grief. Some never returned. The sea, they whispered, had swallowed them whole.\n\nThis was the tax the Dragon King levied on the human world: not gold, not grain, but innocence itself. And no one — not Li Jing, not the Emperor\u2019s ministers, not the bravest warrior in all the land — had ever dared to refuse.",
        zh: "东海深处的万顷波涛之下，坐落着东海龙王敖广的水晶宫——一座由珊瑚为柱、玉石为瓦、幽冷荧光为饰的海底宫殿。敖广绝非寻常的水域之主；他是一位深海帝王，威权绝对，域中万物莫不敬畏。\n\n然而敖广的贪欲永无止境。他索要的贡品不仅有谷物、香火与美玉，更有一样极为恐怖的东西：童男童女。每一年，陈塘关的百姓都必须将年幼的男女孩童送入大海，作为献给龙王的祭品。违抗者将面临洪水、旱灾与足以夷平村庄的狂暴风雨。\n\n夜叉将领李根日夜巡游于近海水域，手持铁棒，目光扫视着下一个祭品。黄昏时分，穿着红色节庆衣裳的孩子们被带到海边，哭声不绝，他们的父母站在身后，面容悲恸如刀刻。有些孩子再也没有回来。大海，人们低声说，把他们整个吞没了。\n\n这便是龙王向人间征收的赋税：不是黄金，不是粮食，而是童真本身。而没有人——不是李靖，不是朝廷重臣，不是全天下最勇猛的武士——曾敢拒绝。",
        pinyin: "Dōng hǎi shēn chù de wàn qǐng bō tāo zhī xià, zuò luò zhe Dōng hǎi lóng wáng Áo Guǎng de shuǐ jīng gōng — yī zuò yóu shān hú wéi zhù, yù shí wéi wǎ, yōu lěng yíng guāng wéi shì de hǎi dǐ gōng diàn. Áo Guǎng jué fēi xún cháng de shuǐ yù zhī zhǔ; tā shì yī wèi shēn hǎi dì wáng, wēi quán jué duì, yù zhōng wàn wù mò bù jìng wèi.\n\nRán ér Áo Guǎng de tān yù yǒng wú zhǐ jìng. Tā suǒ yào de gòng pǐn bù jǐn yǒu gǔ wù, xiāng huǒ yǔ měi yù, gèng yǒu yī yàng jí wéi kǒng bù de dōng xi: tóng nán tóng nǚ. Měi nián, Chén Táng Guān de bǎi xìng dōu bì xū jiāng nián yòu de nán nǚ hái tóng sòng rù dà hǎi, zuò wéi xiàn gěi lóng wáng de jì pǐn. Wéi kàng zhě jiāng miàn lín hóng shuǐ, hàn zāi yǔ zú yǐ yí píng cūn zhuāng de kuáng bào fēng yǔ.\n\nYè chā jiàng lǐng lǐ gēn rì yè xún luó yú jìn hǎi shuǐ yù, shǒu chí tiě bàng, mù guāng sǎo shì zhe xià yī gè jì pǐn. Huáng hūn shí fèn, chuān zhe hóng sè jié qìng yī shang de hái zi men bèi dài dào hǎi biān, kū shēng bù jué, tā men de fù mǔ zhàn zài shēn hòu, miàn róng bēi tòng rú dāo kè. Yǒu xiē hái zi zài yě méi yǒu huí lái. Dà hǎi, rén men dī shēng shuō, bǎ tā men zhěng gè tūn mò le.\n\nZhè biàn shì lóng wáng xiàng rén jiān zhēng shōu de fù shuì: bù shì huáng jīn, bù shì liáng shí, ér shì tóng zhēn běn shēn. Ér méi yǒu rén — bù shì Lì Jìng, bù shì cháo tíng zhòng chén, bù shì quán tiān xià zuì yǒng měng de wǔ shì — céng gǎn jù jué."
      }
    },

    // ─────────────────────────────────────
    // Chapter 3 — The Boy at the Sea
    // ─────────────────────────────────────
    {
      id: 3,
      title: {
        en: "The Boy at the Sea",
        zh: "海边的少年",
        pinyin: "Hǎi Biān de Shào Nián"
      },
      image: "chapter-3.webp",
      content: {
        en: "Years passed, and Nezha grew into a brave, headstrong boy of seven — small in stature but fierce in spirit, with the Universe Ring always at his side and the Red Armillary Sash trailing from his wrist like a ribbon of living flame.\n\nOne sweltering summer day, he asked his mother for permission to play by the sea. Lady Yin, weary from worry, consented — but told him to take the family servant with him. Nezha agreed, though he had no intention of sharing his adventure.\n\nAt the shore, the Nine-Bend Stream emptied into the open ocean, its warm current lapping against ancient stones. Nezha stripped off his outer garments and waded in, letting the water rise to his knees. The heat of the day vanished. He laughed, splashed, and then — without thinking — let the Red Armillary Sash trail into the current.\n\nThe sash, alive with elemental power, sent tremors through the water. The ocean floor shuddered. Coral pillars cracked. In the Crystal Palace far below, chandeliers swung and fish scattered in terror. Ao Guang, Dragon King of the East Sea, felt his throne shake beneath him.\n\n\u201cSomeone is disturbing the sea,\u201d he growled. And he sent his Yaksha general, Li Gen, to investigate.\n\nNezha saw the creature emerge from the depths — a grotesque, club-wielding monster with scales like iron and eyes like burning coals. It pointed its weapon at the boy and bellowed: \u201cChild! You dare disturb the Dragon King\u2019s waters? You will be punished!\u201d\n\nNezha, startled but unafraid, raised the Universe Ring. \u201cI was only bathing,\u201d he said, his voice calm. \u201cBut since you come armed, I will defend myself.\u201d And with a single throw, the golden ring struck the Yaksha and sent it crashing into the waves, never to rise again.",
        zh: "岁月流转，哪吒渐渐长成了一个勇敢而倔强的七岁少年——身形虽小，却气势凌人，乾坤圈时刻不离身侧，混天绫自腕间垂下，宛如一条燃烧着的活火焰。\n\n一个闷热难耐的夏日，他向母亲请求去海边嬉戏。殷夫人虽忧心忡忡，终究允了——却叮嘱他带上家中仆从同行。哪吒口中答应，心中却另有盘算。\n\n到了海边，九湾河汇入汪洋大海，温暖的潮水拍打着嶙峋的古石。哪吒脱去外衫，涉水而入，让海水漫至膝盖。白日的暑气顿时消散。他笑着、扑腾着，而后——未经多想——将混天绫垂入了潮流之中。\n\n那混天绫蕴含着原始的神力，一入水便激起层层震颤。海底山摇地动，珊瑚柱纷纷碎裂。远处的水晶宫内，琉璃灯盏剧烈摇晃，鱼群惊惶四散奔逃。东海龙王敖广只觉身下的宝座猛然颤抖。\n\n\u201c何人搅扰大海？\u201d他怒声咆哮，随即便派出了夜叉将领李根前去查探。\n\n哪吒只见一个庞然大物从深渊中浮出——那是一个手持铁棒的丑陋怪物，鳞片坚硬如铁，双目赤红如烧焦的炭火。它将武器指向少年，怒吼道：\u201c大胆小儿！竟敢搅乱龙王的水域？你必将受到惩罚！\u201d\n\n哪吒虽吃了一惊，却并无惧色，当即举起乾坤圈。\u201c我不过是洗个澡，\u201d他语气平静地说道，\u201c但既然你带了兵器来，我便自卫。\u201d话音未落，金色圆环飞出，正中夜叉，将其击入滔天巨浪之中，再也没有浮上来。",
        pinyin: "Suì yuè liú zhuǎn, Né zhā jiàn jiàn zhǎng chéng le yī gè yǒng gǎn ér jué jiàng de qī suì shào nián — shēn xíng suī xiǎo, què qì shì líng rén, qián kūn quān shí kè bù lí shēn cè, hùn tiān líng zì wàn jiān chuí xià, wǎn rán yī tiáo rán shāo zhe de huó huǒ yàn.\n\nYī gè mēn rè nán nài de xià rì, tā xiàng mǔ qīn qǐng qiú qù hǎi biān xī xì. Yīn fū rén suī yōu xīn chōng chōng, zhōng jiū yǔn le — què dīng zhǔ tā dài shàng jiā zhōng pú cóng tóng xíng. Né zhā kǒu zhōng dā ying, xīn zhōng què lìng yǒu pán suàn.\n\nDào le hǎi biān, jiǔ wān hé huì rù wāng yáng dà hǎi, wēn nuǎn de cháo shuǐ pāi dǎ zhe lín xún de gǔ shí. Né zhā tuō qù wài shān, shè shuǐ ér rù, ràng hǎi shuǐ màn zhì xī gài. Bái rì de shǔ qì dùn shí xiāo sàn. Tā xiào zhe, pū téng zhe, ér hòu — wèi jīng duō xiǎng — jiàng hùn tiān líng chuí rù le cháo liú zhī zhōng.\n\nNà hùn tiān líng yùn hán zhe yuán shǐ de shén lì, yī rù shuǐ biàn jī qǐ céng céng zhèn chàn. Hǎi dǐ shān yáo dì dòng, shān hú zhù fēn fēn suì liè. Yuǎn chù de shuǐ jīng gōng nèi, liú lí dēng zhǎn jù liè yáo huàng, yú qún jīng huáng sì sàn bēn táo. Dōng hǎi lóng wáng Áo Guǎng zhǐ jué shēn xià de bǎo zuò měng rán chàn dǒu.\n\n\u201cHé rén jiǎo rǎo dà hǎi?\u201d tā nù shēng páo xiào, suí jí biàn pài chū le yè chā jiàng lǐng lǐ gēn qián qù chá tàn.\n\nNé zhā zhǐ jiàn yī gè páng rán dà wù cóng shēn yuān zhōng fú chū — nà shì yī gè shǒu chí tiě bàng de chǒu lòu guài wù, lín piàn jiān yìng rú tiě, shuāng mù chì hóng rú shāo jiāo de tàn huǒ. Tā jiāng wǔ qì zhǐ xiàng shào nián, nù hǒu dào: \u201cDà dǎn xiǎo er! Jìng gǎn jiǎo luàn lóng wáng de shuǐ yù? Nǐ bì jiāng shòu dào chéng fá!\u201d\n\nNé zhā suī chī le yī jīng, què bìng wú jù sè, dāng jí jǔ qǐ qián kūn quān. \u201cWǒ bù guò shì xǐ gè zǎo,\u201d tā yǔ qì píng jìng de shuō dào, \u201cdàn jì rán nǐ dài le bīng qì lái, wǒ biàn zì wèi.\u201d Huà yīn wèi luò, jīn sè yuán huán fēi chū, zhèng zhòng yè chā, jiāng qí jī rù tāo tiān jù làng zhī zhōng, zài yě méi yǒu fú shàng lái."
      }
    },

    // ─────────────────────────────────────
    // Chapter 4 — The Death of Ao Bing
    // ─────────────────────────────────────
    {
      id: 4,
      title: {
        en: "The Death of Ao Bing",
        zh: "敖丙之死",
        pinyin: "Áo Bǐng Zhī Sǐ"
      },
      image: "chapter-4.webp",
      content: {
        en: "Word of the Yaksha\u2019s death reached the Crystal Palace like a thunderclap. Ao Guang, the Dragon King, was furious — but it was his third son, Ao Bing, who rose to answer the challenge.\n\nAo Bing was everything Nezha was not: tall, cold, imperial, clad in dragon-scale armour that gleamed like deep-sea jade. He carried a trident forged in the palace furnaces, and his eyes held the contempt of a prince who had never known defeat. He surfaced before Nezha on the shore of Chentang Pass, his soldiers forming a crescent behind him in the churning water.\n\n\u201cYou have slain the Yaksha Li Gen,\u201d Ao Bing said, his voice steady and hard as stone. \u201cYou have disturbed the Dragon King\u2019s waters. Surrender now, or face the consequence.\u201d\n\nNezha looked at the prince — at his arrogance, his weapons, the cold indifference in his eyes. Behind Ao Bing, Nezha could see the shadow of a system that demanded children as offerings, that flooded villages when its tribute went unpaid. \u201cYour father takes children from their mothers,\u201d Nezha said quietly. \u201cThe Yaksha came to punish me for bathing. And now you come to punish me for defending myself. Is this justice?\u201d\n\nAo Bing did not answer with words. He lunged.\n\nThe battle was fierce and brief. Ao Bing fought with the training of a prince — precise, disciplined, lethal. But Nezha fought with something else: the raw, untrained power of the Spirit Pearl, wielded by a child who did not yet understand the limits of his own strength. The Universe Ring blazed gold. The Red Armillary Sash coiled like a serpent. The waves rose and fell. And when it was over, Ao Bing lay still upon the sand, his armour shattered, his life extinguished.\n\nNezha, breathing hard, pulled the dragon tendons from Ao Bing\u2019s body. He held them up, glistening in the sunlight, and thought: Father would make a fine belt from these. He did not yet understand what he had done.",
        zh: "夜叉之死的消息如惊雷般传入水晶宫。东海龙王敖广暴怒至极——然而挺身而出应战的，是他的三太子敖丙。\n\n敖丙与哪吒判若两人：身量高挑，气质冷峻，通身帝王风范，身披龙鳞战甲，闪烁着如深海碧玉般的光泽。他手持龙宫熔炉锻造的三叉戟，目中尽是一个从未尝过败绩的王子的轻蔑。他在陈塘关海岸浮出水面，身后虾兵蟹将排列成弯月阵型。\n\n\u201c你杀了夜叉李根，\u201d敖丙声如铁石，语气沉稳而冰冷，\u201c你搅乱了龙王的水域。现在投降，否则后果自负。\u201d\n\n哪吒注视着这位太子——注视着他的傲慢、他的兵器、他眼中那冷漠至极的神情。在敖丙身后，哪吒看见了一个向孩童索取祭品的制度的阴影，看见了那个一旦贡品不足便以洪水淹没村庄的暴政。\u201c你的父亲从母亲怀中夺走孩子，\u201d哪吒平静地说，\u201c夜叉来是为了惩罚我在海中沐浴。而你现在来惩罚我自卫。这难道就是所谓的正义？\u201d\n\n敖丙没有用言语作答。他猛然扑了上来。\n\n这场战斗激烈而短暂。敖丙以王子的标准武艺作战——精准、凌厉、招招致命。但哪吒倚仗的是另一种力量：灵珠那浑然天成的原始之力，由一个尚不自知自身力量极限的孩子所驾驭。乾坤圈烈焰金光，混天绫如灵蛇般翻卷缠绕。海浪此起彼伏，惊涛拍岸。当一切尘埃落定，敖丙仰面躺在沙地上，战甲碎裂，生命已尽。\n\n哪吒气喘吁吁，从敖丙的身躯中抽出了龙筋。他将龙筋举过头顶，在阳光下闪烁着耀眼的光泽，心想：这倒可以给父亲做一条好腰带。他此时还不明白，自己究竟做下了什么。",
        pinyin: "Yè chā zhī sǐ de xiāo xi rú jīng léi bān chuán rù shuǐ jīng gōng. Dōng hǎi lóng wáng Áo Guǎng bào nù zhì jí — rán ér tǐng shēn ér chū yìng zhàn de, shì tā de sān tài zǐ Áo Bǐng.\n\nÁo Bǐng yǔ Né zhā pàn ruò liǎng rén: shēn liàng gāo tiāo, qì zhì lěng jùn, tōng shēn dì wáng fēng fàn, shēn pī lóng lín zhàn jiǎ, shǎn shuò zhe rú shēn hǎi bì yù bān de guāng zé. Tā shǒu chí lóng gōng róng lú duàn zào de sān chā jǐ, mù zhōng jìn shì yī gè cóng wèi cháng guò bài jì de wáng zǐ de qīng miè. Tā zài Chén Táng Guān hǎi àn fú chū shuǐ miàn, shēn hòu xiā bīng xiè jiàng pái liè chéng wān yuè zhèn xíng.\n\n\u201cNǐ shā le yè chā lǐ gēn,\u201d Áo Bǐng shēng rú tiě shí, yǔ qì chén wěn ér bīng lěng, \u201cNǐ jiǎo luàn le lóng wáng de shuǐ yù. Xiàn zài tóu xiáng, fǒu zé hòu guǒ zì fù.\u201d\n\nNé zhā zhù shì zhe zhè wèi tài zǐ — zhù shì zhe tā de ào màn, tā de bīng qì, tā yǎn zhōng nà lěng mò zhì jí de shén qíng. Zài Áo Bǐng shēn hòu, Né zhā kàn jiàn le yī gè xiàng tóng hái suǒ qǔ jì pǐn de zhì dù de yīn yǐng, kàn jiàn le nà gè yī dàn gòng pǐn bù zú biàn yǐ hóng shuǐ yān mò cūn zhuāng de bào zhèng. \u201cNǐ de fù qīn cóng mǔ qīn huái zhōng duó zǒu hái zi,\u201d Né zhā píng jìng de shuō, \u201cyè chā lái shì wèi le chéng fá wǒ zài hǎi zhōng mù yù. Ér nǐ xiàn zài lái chéng fá wǒ zì wèi. Zhè nán dào jiù shì suǒ wèi de zhèng yì?\u201d\n\nÁo Bǐng méi yǒu yòng yán yǔ zuò dá. Tā měng rán pū le shàng qù.\n\nZhè cháng zhàn dòu jī liè ér duǎn zàn. Áo Bǐng yǐ wáng zǐ de biāo zhǔn wǔ yì zuò zhàn — jīng zhǔn, líng lì, zhāo zhāo zhì mìng. Dàn Né zhā yǐ zhàng de shì lìng yī zhǒng lì liàng: líng zhū nà hún rán tiān chéng de yuán shǐ zhī lì, yóu yī gè shàng bù zì zhī zì shēn lì liàng jí xiàn de hái zi suǒ jià yù. Qián kūn quān liè yàn jīn guāng, hùn tiān líng rú líng shé bān fān juǎn chán rào. Hǎi làng cǐ qǐ bǐ fú, jīng tāo pāi àn. Dāng yī qiè chén āi luò dìng, Áo Bǐng yǎng miàn tǎng zài shā dì shàng, zhàn jiǎ suì liè, shēng mìng yǐ jìn.\n\nNé zhā qì chuǎn xū xū, cóng Áo Bǐng de shēn qū zhōng chōu chū le lóng jīn. Tā jiāng lóng jīn jǔ guò tóu dǐng, zài yáng guāng xià shǎn shuò zhe yào yǎn de guāng zé, xīn xiǎng: zhè dào kě yǐ gěi fù qīn zuò yī tiáo hǎo yāo dài. Tā cǐ shí hái bù míng bai, zì jǐ jiū jìng zuò xià le shén me."
      }
    },

    // ─────────────────────────────────────
    // Chapter 5 — The Four Kings at the Gate
    // ─────────────────────────────────────
    {
      id: 5,
      title: {
        en: "The Four Kings at the Gate",
        zh: "四海龙王临关",
        pinyin: "Sì Hǎi Lóng Wáng Lín Guān"
      },
      image: "chapter-5.webp",
      content: {
        en: "When Ao Guang beheld the tendons of his son — the Dragon King\u2019s tendons, returned like a trophy — his grief erupted into a rage that shook the four seas. He flew to the Jade Emperor\u2019s celestial court and laid his complaint before the throne: the boy Nezha had slain his Yaksha, murdered his son, and defied the authority of the Dragon Kings.\n\nThe Jade Emperor, moved by Ao Guang\u2019s fury, granted permission for all four Dragon Kings to march upon Chentang Pass and demand Li Jing surrender his son.\n\nThey came at dawn. Ao Guang of the East Sea in blue dragon robes, Ao Qin of the South Sea in white, Ao Run of the West Sea in black, Ao Shun of the North Sea in red — four emperors of the deep, standing in a line before the fortress gates like pillars of judgement. Behind them, the sky darkened. Thunder rolled. Rain fell in sheets. The sea itself rose and pressed against the walls of Chentang Pass, as if the ocean had come to collect its debt.\n\nLi Jing knelt before them, his armour heavy with rain, his face hollow with the knowledge of what was being asked. Behind him, Lady Yin wept silently. The people of Chentang Pass gathered at the gates, their faces pale, their children clutching at their robes.\n\n\u201cSurrender the boy,\u201d Ao Guang commanded, his voice resonating like the tolling of a great bell. \u201cSurrender Nezha, or Chentang Pass will be swallowed by the sea.\u201d\n\nAnd in that moment, Nezha — who had been standing silent behind his father — stepped forward. He looked at the four Dragon Kings. He looked at his father, broken and kneeling. He looked at the people of Chentang Pass, whose children would be the next tribute if he refused.\n\nAnd he understood.",
        zh: "当敖广看见了儿子的龙筋——那龙王的血脉，竟被当作战利品般送回——他的悲痛化作了震怒四海的滔天怒火。他飞往玉皇大帝的天庭，在御座前呈上控告：少年哪吒杀了他的夜叉、害了他的三太子、藐视了四海龙王的威严。\n\n玉帝感于敖广的震怒，恩准四海龙王同时兴师问罪，强令李靖交出其子。\n\n他们在黎明时分到来。东海龙王敖广身着蓝色龙袍，南海龙王敖秦着白，西海龙王敖润着黑，北海龙王敖顺着红——四位深海帝王一字排开，如四根审判之柱矗立在陈塘关的城门之前。在他们身后，天空骤暗，雷声隆隆，大雨倾盆。大海本身也汹涌而起，撞击着陈塘关的城墙，仿佛大洋亲自前来索取它的债务。\n\n李靖跪伏在他们面前，战甲被雨水浸透，面容因即将到来的命运而空洞绝望。在他身后，殷夫人默默垂泪。陈塘关的百姓聚集在城门口，面如死灰，孩子们紧紧抓着父母的衣襟。\n\n\u201c交出那个孩子，\u201d敖广威严下令，声音如洪钟大吕般回荡。\u201c交出哪吒，否则陈塘关将被大海吞没。\u201d\n\n就在那一刻，哪吒——一直沉默地站在父亲身后——迈步走了出来。他望向四位龙王。他望向跪倒在地、心碎欲绝的父亲。他望向陈塘关的百姓，他们的孩子将成为下一批祭品——如果他拒绝的话。\n\n他明白了。",
        pinyin: "Dāng Áo Guǎng kàn jiàn le ér zi de lóng jīn — nà lóng wáng de xuè mài, jìng bèi dāng zuò zhàn lì pǐn bān sòng huí — tā de bēi tòng huà zuò le zhèn nù sì hǎi de tāo tiān nù huǒ. Tā fēi wǎng yù huáng dà dì de tiān tíng, zài yù zuò qián chéng shàng kòng gào: shào nián Né zhā shā le tā de yè chā, hài le tā de sān tài zǐ, miǎo shì le sì hǎi lóng wáng de wēi yán.\n\nYù dì gǎn yú Áo Guǎng de zhèn nù, ēn zhǔn sì hǎi lóng wáng tóng shí xīng shī wèn zuì, qiáng lìng Lì Jìng jiāo chū qí zǐ.\n\nTā men zài lí míng shí fèn dào lái. Dōng hǎi lóng wáng Áo Guǎng shēn zhuó lán sè lóng páo, Nán hǎi lóng wáng Áo Qín zhuó bái, Xī hǎi lóng wáng Áo Rùn zhuó hēi, Běi hǎi lóng wáng Áo Shùn zhuó hóng — sì wèi shēn hǎi dì wáng yī zì pái kāi, rú sì gēn shěn pàn zhī zhù chù lì zài Chén Táng Guān de chéng mén zhī qián. Zài tā men shēn hòu, tiān kōng zhòu àn, léi shēng lóng lóng, dà yǔ qīng pén. Dà hǎi běn shēn yě xiōng yǒng ér qǐ, zhuàng jī zhe Chén Táng Guān de chéng qiáng, fǎng fú dà yáng qīn zì qián lái suǒ qǔ tā de zhài wù.\n\nLì Jìng guì fú zài tā men miàn qián, zhàn jiǎ bèi yǔ shuǐ jìn tòu, miàn róng yīn jí jiāng dào lái de mìng yùn ér kōng dòng jué wàng. Zài tā shēn hòu, Yīn fū rén mò mò chuí lèi. Chén Táng Guān de bǎi xìng jù jí zài chéng mén kǒu, miàn rú sǐ huī, hái zi men jǐn jǐn zhuā zhe fù mǔ de yī jīn.\n\n\u201cJiāo chū nà gè hái zi,\u201d Áo Guǎng wēi yán xià lìng, shēng yīn rú hóng zhōng dà lǚ bān huí dàng. \u201cJiāo chū Né zhā, fǒu zé Chén Táng Guān jiāng bèi dà hǎi tūn mò.\u201d\n\nJiù zài nà yī kè, Né zhā — yī zhí chén mò de zhàn zài fù qīn shēn hòu — mài bù zǒu le chū lái. Tā wàng xiàng sì wèi lóng wáng. Tā wàng xiàng guì zài dǎo dì, xīn suì yù jué de fù qīn. Tā wàng xiàng Chén Táng Guān de bǎi xìng, tā men de hái zi men jiāng chéng wéi xià yī pī jì pǐn — rú guǒ tā jù jué de huà.\n\nTā míng bai le."
      }
    },

    // ─────────────────────────────────────
    // Chapter 6 — Returning Flesh and Bone
    // ─────────────────────────────────────
    {
      id: 6,
      title: {
        en: "Returning Flesh and Bone",
        zh: "析骨还父",
        pinyin: "Xī Gǔ Huán Fù"
      },
      image: "chapter-6.webp",
      content: {
        en: "Nezha stepped forward into the rain, his small frame dwarfed by the four Dragon Kings and the fortress walls. The people of Chentang Pass watched in silence. His parents stood behind him, Li Jing with his head bowed, Lady Yin with tears streaming down her face.\n\n\u201cThis is my doing,\u201d Nezha said, his voice clear and steady above the rain. \u201cI killed the Yaksha. I killed Ao Bing. I acted alone. Let the people of Chentang Pass go free.\u201d\n\nAo Guang\u2019s eyes narrowed. \u201cThe debt must be paid in full. You cannot repay a Dragon King\u2019s son with mere words.\u201d\n\nNezha looked at his father — at the man who had drawn his sword the night Nezha was born, at the man who feared him, at the man who loved him despite everything. \u201cThen I will repay it with what I owe,\u201d Nezha said.\n\nHe drew the short blade from his belt.\n\nThe rain fell harder. The wind howled. Lady Yin screamed. But Nezha was calm — calm in a way that a seven-year-old should not be, calm in a way that made the Dragon Kings step back. He held the blade before him and spoke the words that would echo through two thousand years of Chinese memory:\n\n\u201cI return my flesh to my mother, and my bones to my father. From this day, I owe you nothing — and you owe me nothing.\u201d\n\nWhat followed was an act of such terrible, quiet courage that even Ao Guang could not watch. Nezha, with steady hands, carved his own flesh from his bones — not in fury, not in despair, but in perfect, devastating resolve. He gave back to his parents what they had given him, piece by piece, until nothing remained.\n\nThe rain stopped. The thunder fell silent. The sea withdrew.\n\nAnd Nezha was gone.",
        zh: "哪吒步入大雨之中，他小小的身躯在四海龙王与巍峨城墙的映衬下显得微不足道。陈塘关的百姓们沉默地注视着。他的父母站在他身后——李靖低垂着头，殷夫人泪流满面。\n\n\u201c这是我一人所为，\u201d哪吒的声音在雨声之上清晰而坚定，\u201c夜叉是我杀的。敖丙也是我杀的。一切由我一人承担。请放陈塘关的百姓一条生路。\u201d\n\n敖广目光如刃。\u201c债务必须全额清偿。龙王之子的命，岂是几句言语就能抵偿的。\u201d\n\n哪吒望向父亲——望向那个在他出生之夜拔剑相向的男人，望向那个畏惧他的男人，望向那个即便如此依然深爱着他的男人。\u201c那么，我便以我所欠之物来偿还，\u201d哪吒说。\n\n他从腰间抽出了短刀。\n\n雨势更猛，狂风怒号。殷夫人发出了一声撕心裂肺的惨叫。但哪吒却出奇地冷静——冷静得不像一个七岁的孩子，冷静得令四位龙王都不由自主地向后退了一步。他手持短刀，说出了那句将回响两千余年的话语：\n\n\u201c析肉还母，析骨还父。从今以后，我欠你们的，你们也欠我的——一笔勾销。\u201d\n\n接下来发生的，是一种如此沉静、如此可怖的勇气，连敖广都不忍直视。哪吒以稳定的双手，将自己的血肉从骨骼上一点一点地割下来——不是出于愤怒，不是出于绝望，而是出于一种完美的、令人心碎的决绝。他将父母赐予他的一切，一点一点地归还，直至什么也不剩。\n\n雨停了。雷声止息。大海退去。\n\n哪吒消失了。",
        pinyin: "Né zhā bù rù dà yǔ zhī zhōng, tā xiǎo xiǎo de shēn qū zài sì hǎi lóng wáng yǔ wēi é chéng qiáng de yìng chèn xià xiǎn de wēi bù zú dào. Chén Táng Guān de bǎi xìng men chén mò de zhù shì zhe. Tā de fù mǔ zhàn zài tā shēn hòu — Lì Jìng dī chuí zhe tóu, Yīn fū rén lèi liú mǎn miàn.\n\n\u201cZhè shì wǒ yī rén suǒ wéi,\u201d Né zhā de shēng yīn zài yǔ shēng zhī shàng qīng xī ér jiān dìng, \u201cyè chā shì wǒ shā de. Áo Bǐng yě shì wǒ shā de. Yī qiè yóu wǒ yī rén chéng dān. Qǐng fàng Chén Táng Guān de bǎi xìng yī tiáo shēng lù.\u201d\n\nÁo Guǎng mù guāng rú rèn. \u201cZhài wù bì xū quán é qīng cháng. Lóng wáng zhī zǐ de mìng, qǐ shì jǐ jù yán yǔ jiù néng dǐ cháng de.\u201d\n\nNé zhā wàng xiàng fù qīn — wàng xiàng nà gè zài tā chū shēng zhī yè bá jiàn xiāng xiàng de nán rén, wàng xiàng nà gè wèi jù tā de nán rén, wàng xiàng nà gè jí biàn rú cǐ yī rán shēn ài zhe tā de nán rén. \u201cNà me, wǒ biàn yǐ wǒ suǒ qiàn zhī wù lái cháng huán,\u201d Né zhā shuō.\n\nTā cóng yāo jiān chōu chū le duǎn dāo.\n\nYǔ shì gèng měng, kuáng fēng nù háo. Yīn fū rén fā chū le yī shēng sī xīn liè fèi de cǎn jiào. Dàn Né zhā què chū qí de lěng jìng — lěng jìng de bù xiàng yī gè qī suì de hái zi, lěng jìng de lìng sì wèi lóng wáng dōu bù yóu zì zhǔ de xiàng hòu tuì le yī bù. Tā shǒu chí duǎn dāo, shuō chū le nà jù jiāng huí xiǎng liǎng qiān yú nián de huà yǔ:\n\n\u201cXī ròu huán mǔ, xī gǔ huán fù. Cóng jīn yǐ hòu, wǒ qián nǐ men de, nǐ men yě qián wǒ de — yī bǐ gōu xiāo.\u201d\n\nJiē xià lái fā shēng de, shì yī zhǒng rú cǐ chén jìng, rú cǐ kě pà de yǒng qì, lián Áo Guǎng dōu bù rěn zhí shì. Né zhā yǐ wěn dìng de shuāng shǒu, jiāng zì jǐ de xuè ròu cóng gǔ gé shàng yī diǎn yī diǎn de gē xià lái — bù shì chū yú fèn nù, bù shì chū yú jué wàng, ér shì chū yú yī zhǒng wán měi de, lìng rén xīn suì de jué jué. Tā jiāng fù mǔ cì yǔ tā de yī qiè, yī diǎn yī diǎn de guī huán, zhí zhì shén me yě bù shèng.\n\nYǔ tíng le. Léi shēng zhǐ xī. Dà hǎi tuì qù le.\n\nNé zhā xiāo shī le."
      }
    },

    // ─────────────────────────────────────
    // Chapter 7 — The Lotus Reborn
    // ─────────────────────────────────────
    {
      id: 7,
      title: {
        en: "The Lotus Reborn",
        zh: "莲花化身",
        pinyin: "Lián Huā Huà Shēn"
      },
      image: "chapter-7.webp",
      content: {
        en: "Nezha\u2019s soul, freed from the weight of flesh and bone, drifted upward through rain and cloud to the peak of Kunlun Mountain — the sacred abode of the immortals, where peach trees bloomed eternal and the rivers flowed with starlight.\n\nThere, in a cave wreathed in jade-green mist, Taiyi Zhenren waited. He had felt the moment of his disciple\u2019s death like a blade through his own heart. Now he gathered what he needed: lotus roots, pale and luminous, pulled from the Pure Land pool; lotus leaves, broad as shields, green as ancient jade; and lotus petals, pink as dawn, delicate as a breath.\n\nHe arranged them in the shape of a body — root for bone, leaf for skin, petal for flesh. Then he placed Nezha\u2019s soul within this lotus vessel and breathed upon it.\n\nThe lotus stirred. Colour flooded through it — pink deepening to the warmth of living skin, green fading to the softness of a child\u2019s veins. The figure opened its eyes.\n\nNezha rose. He was the same, and yet utterly changed. His body was no longer made of mortal flesh but of lotus — pure, unbreakable, reborn. The Lotus Body, as the immortals would call it.\n\nTaiyi Zhenren smiled through his tears. He placed two new weapons in Nezha\u2019s hands: the Fire-Tipped Spear, its blade glowing like a captured sunset, and the Wind-Fire Wheels — two blazing discs that hovered at his feet, humming with the heat of a thousand forges.\n\n\u201cYou are free of the debt of birth,\u201d the immortal said. \u201cYou owe nothing to anyone. Now go — and fight for those who cannot fight for themselves.\u201d",
        zh: "哪吒的灵魂挣脱了血肉与骨骼的重负，穿越雨云，向上飘升，最终抵达了昆仑山的巅峰——那是仙人居住的神圣之地，桃树四季常开，河水流淌着星光。\n\n在昆仑山上一处被碧绿雾气缭绕的洞穴中，太乙真人一直在等候。弟子殒命的那一刻，他便如利刃穿心般感知到了。此刻，他取出了所需的材料：莲藕——从净土莲池中掘出，洁白而莹润；莲叶——大如盾牌，绿如古玉；莲花花瓣——粉如晨曦，轻柔若一缕微风。\n\n他以莲藕为骨，莲叶为肤，花瓣为肉，将它们摆成人形。然后，他将哪吒的灵魂安放在这具莲花躯壳之中，对着它轻轻吹了一口气。\n\n莲花微微颤动。色彩如潮水般涌入——粉红色渐渐化为活人肌肤的温润，翠绿色缓缓褪去，露出了孩童血管的柔软脉络。莲花人形睁开了眼睛。\n\n哪吒重新站了起来。他依然是他，却又截然不同。他的躯体不再是凡胎肉身，而是由莲花化成——纯洁无瑕，坚不可摧，浴火重生。这便是仙人们所说的\u201c莲花化身\u201d。\n\n太乙真人含泪微笑了。他将两件全新的法宝放入哪吒手中：火尖枪——枪刃如落日般灼灼发光；风火轮——两面烈焰翻腾的圆盘悬浮在他脚下，发出千座熔炉般的灼热之音。\n\n\u201c你已经偿清了出生之债，\u201d仙人说道，\u201c你不欠任何人。现在去吧——为那些无法自卫的人而战。\u201d",
        pinyin: "Né zhā de líng hún zhēng tuō le xuè ròu yǔ gǔ gé de zhòng fù, chuān yuè yǔ yún, xiàng shàng piāo shēng, zuì zhōng dǐ dá le Kūn lún shān de diān fēng — nà shì xiān rén jū zhù de shén shèng zhī dì, táo shù sì jì cháng kāi, hé shuǐ liú tǎng zhe xīng guāng.\n\nZài Kūn lún shān shàng yī chù bèi bì lǜ wù qì liáo rào de dòng xué zhōng, Tài yǐ zhēn rén yī zhí zài děng hòu. Dì zǐ yǔn mìng de nà yī kè, tā biàn rú lì rèn chuān xīn bān gǎn zhī dào le. Cǐ kè, tā qǔ chū le suǒ xū de cái liào: lián ǒu — cóng jìng tǔ lián chí zhōng jué chū, jié bái ér yíng rùn; lián yè — dà rú dùn pái, lǜ rú gǔ yù; lián huā huā bàn — fěn rú chén xī, qīng róu ruò yī lǚ wēi fēng.\n\nTā yǐ lián ǒu wéi gǔ, lián yè wéi fū, huā bàn wéi ròu, jiāng tā men bǎi chéng rén xíng. Rán hòu, tā jiāng Né zhā de líng hún ān fàng zài zhè jù lián huā qū ké zhī zhōng, duì zhe tā qīng qīng chuī le yī kǒu qì.\n\nLián huā wēi wēi chàn dòng. Sè cǎi rú cháo shuǐ bān yǒng rù — fěn hóng sè jiàn jiàn huà wéi huó rén jī fū de wēn rùn, cuì lǜ sè huǎn huǎn tuì qù, lù chū le hái tóng xuè guǎn de róu ruǎn mài luò. Lián huā rén xíng zhēng kāi le yǎn jīng.\n\nNé zhā chóng xīn zhàn le qǐ lái. Tā yī rán shì tā, què yòu jié rán bù tóng. Tā de qū tǐ bù zài shì fán tāi ròu shēn, ér shì yóu lián huā huà chéng — chún jié wú xiá, jiān bù kě cuī, yù huǒ chóng shēng. Zhè biàn shì xiān rén men suǒ shuō de莲花化身.\n\nTài yǐ zhēn rén hán lèi wēi xiào le. Tā jiāng liǎng jiàn quán xīn de fǎ bǎo fàng rù Né zhā shǒu zhōng: huǒ jiān qiāng — qiāng rèn rú luò rì bān zhuó zhuó fā guāng; fēng huǒ lún — liǎng miàn liè yàn fān téng de yuán pán xuán fú zài tā jiǎo xià, fā chū qiān zuò róng lú bān de zhuó rè zhī yīn.\n\n\u201cNǐ yǐ jīng cháng qīng le chū shēng zhī zhài,\u201d xiān rén shuō dào, \u201cnǐ bù qián rèn hé rén. Xiàn zài qù ba — wèi nà xiē wú fǎ zì wèi de rén ér zhàn.\u201d"
      }
    },

    // ─────────────────────────────────────
    // Chapter 8 — The Third Lotus Prince
    // ─────────────────────────────────────
    {
      id: 8,
      title: {
        en: "The Third Lotus Prince",
        zh: "莲花三太子",
        pinyin: "Lián Huā Sān Tài Zǐ"
      },
      image: "chapter-8.webp",
      content: {
        en: "Nezha flew back to the sea on the Wind-Fire Wheels, the Fire-Tipped Spear blazing in his hand, the Red Armillary Sash streaming behind him like a wound in the sky. He had no army. He had no fortress. He had only himself — and what himself had become.\n\nHe summoned the Three Heads and Six Arms form, and the sky split open. Six arms, each wielding a weapon. Three heads, each bearing the gaze of someone who had died and returned. The people of Chentang Pass, watching from the shore, fell to their knees — not in fear, but in awe.\n\nThe battle that followed was not a contest. It was a reckoning.\n\nAo Guang, Ao Qin, Ao Run, Ao Shun — the four Dragon Kings of the seas — fought with all the fury of emperors. But Nezha moved through their attacks like wind through water, his spear singing, his ring spinning, his sash coiling and striking. One by one, the Dragon Kings fell. The Crystal Palace cracked and crumbled into the deep. The sea, which had risen to devour Chentang Pass, receded — slowly, then all at once — and the fortress stood dry and whole.\n\nWhen it was done, Nezha hovered above the waves, the Fire-Tipped Spear quiet in his hand. Below him, the people of Chentang Pass cheered — parents lifting their children into the air, tears of relief streaming down faces that had not smiled in years.\n\nNezha descended. He landed before his father.\n\nLi Jing looked at his son — reborn, radiant, more powerful than he had ever been. Father and son regarded each other across a silence that held everything: grief, pride, fear, love. Neither spoke. There were no words for what had passed between them.\n\nBut the people were safe. The sea was calm. And in the years that followed, no Dragon King would ever again demand a child\u2019s life.\n\nNezha became what the legends would call him: Marshal of the Central Altar, the Third Lotus Prince — the boy who shook the sea, who paid the debt of his birth, who rose again from lotus and flame, and who fought for those who could not fight for themselves.\n\nAnd on quiet nights, when the sea is still and the moon is bright, the people of Chentang Pass still tell the story — of the child who was born from a flesh ball, who died for his people, and who returned, not as a mortal, but as something more.\n\nAs something eternal.",
        zh: "哪吒脚踏风火轮飞回东海，火尖枪在他掌中灼灼燃烧，混天绫在身后猎猎飞扬，宛如天幕上一道燃烧的伤口。他没有千军万马。他没有城池堡垒。他只有他自己——以及他已经蜕变成的那个人。\n\n他施展三头六臂的法相，天空骤然裂开。六只手臂，各执一件兵器。三颗头颅，每一颗都带着一个曾经死去又重生之人的目光。陈塘关的百姓们在岸上目睹此景，纷纷跪倒在地——不是出于恐惧，而是出于无上的敬畏。\n\n接下来发生的不是一场战斗。而是一场审判。\n\n敖广、敖秦、敖润、敖顺——四海龙王——以帝王之怒全力作战。但哪吒在他们的攻势中穿行如风过水面，长枪如歌，金环飞旋，红绫缠绕击打。龙王们一个接一个地败下阵来。水晶宫轰然碎裂，崩塌坠入深海。那曾经汹涌而起要吞没陈塘关的大海，缓缓退去——继而骤然全部退去——城关安然无恙，巍然屹立。\n\n当一切尘埃落定，哪吒悬浮于惊涛之上，火尖枪安静地握在他手中。身下，陈塘关的百姓爆发出震天的欢呼——父母们将孩子高高举起，喜悦的泪水从那些已经很久没有展露笑颜的面庞上滚落。\n\n哪吒缓缓降落，落在了父亲面前。\n\n李靖望着自己的儿子——浴火重生，光彩照人，比从前任何时候都更加强大。父子隔着一段沉默对视着，那沉默中承载着一切：悲恸、骄傲、畏惧、深爱。两人谁也没有开口。对于他们之间发生的一切，语言是苍白无力的。\n\n但百姓安然无恙。大海归于平静。在那之后的漫长岁月里，再没有龙王敢索取孩童的性命。\n\n哪吒成为了传说中传颂的那个名字：中坛元帅，莲花三太子——那个震动了大海的孩子，那个偿清了出生之债的孩子，那个从莲花与烈焰中重新站起的孩子，那个为无法自卫之人而战的孩子。\n\n在那些宁静的夜晚，当大海平息、明月当空之时，陈塘关的人们仍然在讲述着这个故事——关于一个从肉球中降生的孩子，一个为百姓赴死的孩子，一个并非以凡人之身、而是以更崇高之姿归来的孩子。\n\n以永恒之姿归来。",
        pinyin: "Né zhā jiǎo tà fēng huǒ lún fēi huí Dōng hǎi, huǒ jiān qiāng zài tā zhǎng zhōng zhuó zhuó rán shāo, hùn tiān líng zài shēn hòu liè liè fēi yáng, wǎn rú tiān mù shàng yī dào rán shāo de shāng kǒu. Tā méi yǒu qiān jūn wàn mǎ. Tā méi yǒu chéng chí bǎo lěi. Tā zhǐ yǒu tā zì jǐ — yǐ jí tā yǐ jīng tuì biàn chéng de nà gè rén.\n\nTā shī zhǎn sān tóu liù bì de fǎ xiàng, tiān kōng zhòu rán liè kāi. Liù zhī shǒu bì, gè zhí yī jiàn bīng qì. Sān kē tóu lú, měi yī kē dōu dài zhe yī gè céng jīng sǐ qù yòu chóng shēng zhī rén de mù guāng. Chén Táng Guān de bǎi xìng men zài àn shàng mù dǔ cǐ jǐng, fēn fēn guì dào zài dì — bù shì chū yú kǒng jù, ér shì chū yú wú shàng de jìng wèi.\n\nJiē xià lái fā shēng de bù shì yī chǎng zhàn dòu. Ér shì yī chǎng shěn pàn.\n\nÁo Guǎng, Áo Qín, Áo Rùn, Áo Shùn — sì hǎi lóng wáng — yǐ dì wáng zhī nù quán lì zuò zhàn. Dàn Né zhā zài tā men de gōng shì zhōng chuān xíng rú fēng guò shuǐ miàn, cháng qiāng rú gē, jīn huán fēi xuán, hóng líng chán rào jī dǎ. Lóng wáng men yī gè jiē yī gè de bài xià zhèn lái. Shuǐ jīng gōng hōng rán suì liè, bēng tā zhuì rù shēn hǎi. Nà céng jīng xiōng yǒng ér qǐ yào tūn mò Chén Táng Guān de dà hǎi, huǎn huǎn tuì qù — jì ér zhòu rán quán bù tuì qù — chéng guān ān rán wú yàng, wēi rán yì lì.\n\nDāng yī qiè chén āi luò dìng, Né zhā xuán fú yú jīng tāo zhī shàng, huǒ jiān qiāng ān jìng de wò zài tā shǒu zhōng. Shēn xià, Chén Táng Guān de bǎi xìng bào fā chū zhèn tiān de huān hū — fù mǔ men jiāng hái zi gāo gāo jǔ qǐ, xǐ yuè de yǎn lèi cóng nà xiē yǐ jīng hěn jiǔ méi yǒu zhǎn lù xiào yán de miàn páng shàng gǔn luò.\n\nNé zhā huǎn huǎn jiàng luò, luò zài le fù qīn miàn qián.\n\nLì Jìng wàng zhe zì jǐ de ér zi — yù huǒ chóng shēng, guāng cǎi zhào rén, bǐ cóng qián rèn hé shí hou dōu gèng jiā qiáng dà. Fù zǐ gé zhe yī duàn chén mò duì shì zhe, nà chén mò zhōng chéng zài zhe yī qiè: bēi tòng, jiāo ào, wèi jù, shēn ài. Liǎng rén shuí yě méi yǒu kāi kǒu. Duì yú tā men zhī jiān fā shēng de yī qiè, yǔ yán shì cāng bái wú lì de.\n\nDàn bǎi xìng ān rán wú yàng. Dà hǎi guī yú píng jìng. Zài nà zhī hòu de màn cháng suì yuè lǐ, zài méi yǒu lóng wáng gǎn suǒ qǔ hái tóng de xìng mìng.\n\nNé zhā chéng wéi le chuán shuō zhōng chuán sòng de nà gè míng zì: Zhōng Tán Yuán Shuài, Lián Huā Sān Tài Zǐ — nà gè zhèn dòng le dà hǎi de hái zi, nà gè cháng qīng le chū shēng zhī zhài de hái zi, nà gè cóng lián huā yǔ liè yàn zhōng chóng xīn zhàn qǐ de hái zi, nà gè wèi wú fǎ zì wèi zhī rén ér zhàn de hái zi.\n\nZài nà xiē níng jìng de yè wǎn, dāng dà hǎi píng xī, míng yuè dāng kōng zhī shí, Chén Táng Guān de rén men réng rán zài jiǎng shù zhe zhè ge gù shì — guān yú yī gè cóng ròu qiú zhōng jiàng shēng de hái zi, yī gè wèi bǎi xìng fù sǐ de hái zi, yī gè bìng fēi yǐ fán rén zhī shēn, ér shì yǐ gèng chóng gāo zhī zī guī lái de hái zi.\n\nYǐ yǒng héng zhī zī guī lái."
      }
    }
  ]
};
